### ISSUE TITLE
Publish this with Datasette?

### ISSUE THREAD

**Issue by simonw** [JelleZijlstra/taxonomy#1]
Hi!

I just saw your lightning talk at PyCon.

Have you seen my Datasette project? It's designed to help people with interesting SQLite databases publish them online... and it looks like you have a really interesting SQLite database!

Here's an example of what that could look like: https://metmuseum.datasettes.com/ (all templates and CSS can be customized)

And here's the documentation: https://datasette.readthedocs.io/en/stable/

If you're interested please let me know if this works for you!

Thanks,

Simon

**Comment by JelleZijlstra** [comment]
Thank you! I'll definitely check this out.

**Comment by JelleZijlstra** [comment]
I got it running locally and it's definitely useful for exploration. A couple of issues I see:
- It doesn't know about my enums, so it just shows "1" and "2" instead of the actual enum names. As far as I can tell there's no config option to fix this.
- Similarly, it doesn't know about the relations between tables, so it shows say the original_citation_id as just an int instead of a reference to the article object. Again as far as I can tell this isn't configurable.

Maybe I can try to contribute fixes for these issues to datasette though!

**Comment by JelleZijlstra** [comment]
Not planning to do this.
